### ISSUE TITLE
Missing file in CelebA dataset?

### ISSUE THREAD

**Issue by pmichel31415** [deepmind/emergent_communication_at_scale#1]
Hi, thanks for releasing this codebase, super useful!

Not a bug per se but I think there is a file missing in the `byol_celeb_a2.tar.gz` archive. Specifically I get this error after trying to load the data:

```
tensorflow.python.framework.errors_impl.NotFoundError: data/byol_celeb_a2/1.0.0/byol_celeb_a2-test.tfrecord-00000-of-00008
```

Upon manual inspection this seems to be the only file missing from the archive. This can also be checked manually with

```
tar -zxvf data/byol_celeb_a2.tar.gz byol_celeb_a2-test.tfrecord-00000-of-00008
```

**Comment by rahmacha** [comment]
Hi, I updated the dataset. it should work now.
Thank you.
